### ISSUE TITLE
Does not support binary data (workaround included)

### ISSUE THREAD

**Issue by jcassee** [adamchainz/treepoem#112]
I am creating Aztec barcodes that contain binary data. I found I needed to perform a trick to decode my data into a string because [treepoem will encode it](https://github.com/YPlan/treepoem/blob/master/treepoem/__init__.py#L115):

```
data=data.decode("ascii", errors="ignore")
```

Maybe treepoem could check if the data is already in bytes.

(Otherwise, great little package. Works out of the box!)

**Comment by adamchainz** [comment]
Makes sense to me... feel like writing a PR? :) :)
