### ISSUE TITLE
Documentation needed for specifying "parse" or "raw" in azteccode

### ISSUE THREAD

**Issue by medios25** [adamchainz/treepoem#117]
Newer to python, but I cannot pass either "raw" or "parse" .

passing:
options={"format":"full", "layers":"4"}  works just fine for specifying a full full Aztec code with 4 layers, but how do you pass the option for parse or raw?

Need documentation on how to accomplish something like below:
options={"parse":"true"}

Is this really easy and I am missing something?

**Comment by adamchainz** [comment]
That should work afaiu, are you getting a particular error? There's nothing special in Python about the strings `"parse"` or `"true"`.

**Comment by adamchainz** [comment]
Hi, if you are still experiencing a problem please open a PR with a failing test.
