### ISSUE TITLE
Test fixtures generate differently on newer versions of ghostscript

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/treepoem#124]
Currently on Travis ghostscript 9.10 is used, and it's compatible with the files in `tests/fixtures/`. However on my Mac I now get version 9.23 and that leads to the tests failing. It seems that one extra pixel is (wrongly?) drawn on newer versions. Perhaps there's some argument we can pass to newer ghostscript versions to preserve the apparently correct older rendering.

**Comment by adamchainz** [comment]
9.10 azteccode

![azteccode-old](https://user-images.githubusercontent.com/857609/43678754-5e1bc8f4-9819-11e8-8154-cc2d42fa4926.png)

9.23 azteccode

![azteccode](https://user-images.githubusercontent.com/857609/43678756-64d6d30a-9819-11e8-8243-ca81de5dff54.png)

🤔

**Comment by jcassee** [comment]
Interestingly, I have been given feedback about my treepoem-generated Aztec codes not being correct (with Ghostscript 9.22). I have been experimenting with the `inkspread` parameter to try and compensate (assumptions...), but unfortunately the feedback look is very slow.

Anyway, as requested in #113, these are the test fixture barcodes that my system (Ubuntu 18.04, Ghostscript 9.22) generates:

azteccode.png:
![azteccode](https://user-images.githubusercontent.com/20749/43690252-87fe4ff4-9907-11e8-9ce5-6c3556fc89d9.png)

code39.png:
![code39](https://user-images.githubusercontent.com/20749/43690253-882da81c-9907-11e8-99da-67ddf48ea344.png)

code128.png:
![code128](https://user-images.githubusercontent.com/20749/43690254-88458752-9907-11e8-9948-fff2788ee30f.png)

interleaved2of5.png:
![interleaved2of5](https://user-images.githubusercontent.com/20749/43690255-88760058-9907-11e8-8d35-08fec7a95082.png)

pdf417.png:
![pdf417](https://user-images.githubusercontent.com/20749/43690256-88a370c4-9907-11e8-9d30-10b84b1ea2e7.png)

qrcode.png:
![qrcode](https://user-images.githubusercontent.com/20749/43690257-88ba3ab6-9907-11e8-8e3b-8f47b060ff5e.png)

**Comment by adamchainz** [comment]
Yeah those all look like they have been smeared like I'm seeing. Did you try downgrading your ghostscript and seeing if that fulfills your user's requirements?

Running here with `{'inkspread': '0.1'}` gets me PNG's that look right, but they're smaller, e.g. I get 76x76 for aztec instead of 78x78 from the old ghostscript:

![azteccode](https://user-images.githubusercontent.com/857609/43704370-b691ce2e-995f-11e8-8788-a8c2ae6d2554.png)

**Comment by jcassee** [comment]
Using Ghostscript 9.18, the Aztec barcode looks better, and is scanned by my app. (The gs 9.22 version (above) is not recognized.)

![azteccode](https://user-images.githubusercontent.com/20749/44408818-70579980-a561-11e8-854d-1199fa8ff996.png)

**Comment by adamchainz** [comment]
Thanks for bisecting it. I've reported upstream in bwipp/postscriptbarcode#94, the maintainer of BWIPP is pretty knowledgable and may be able to help.

**Comment by adamchainz** [comment]
N.B. Travis CI seem to have updated the version of ghostscript on their build containers so this is failing continuously now

**Comment by adamchainz** [comment]
It looks like the fix was released in Ghostscript 9.26. I think some more work is needed to pass different flags to render, potentially by not using PIL any more.

**Comment by adamchainz** [comment]
#499 improved image generation by bypassing the PIL EPS plugin that runs Ghostscript, so this can be considered fixed.
