### ISSUE TITLE
GS1-128 Barcode Generation

### ISSUE THREAD

**Issue by UsmanGorsii** [adamchainz/treepoem#158]
I am trying to generate a GS1-128 barcode but I am running into this exception. 
import treepoem

image = treepoem.generate_barcode(
     barcode_type='gs1-128',  # One of the BWIPP supported codes.
     data=b'0101234567890128TEC-IT',
 )
image.convert('1').save('barcodsawefe.png')

Traceback (most recent call last):
  File "D:/Fiverr/PdfCoupons/test.py", line 14, in <module>
    data=b'0101234567890128TEC-IT',
  File "D:\Fiverr\PdfCoupons\venv\lib\site-packages\treepoem\__init__.py", line 142, in generate_barcode
    bbox_lines = _get_bbox(code)
  File "D:\Fiverr\PdfCoupons\venv\lib\site-packages\treepoem\__init__.py", line 94, in _get_bbox
    raise TreepoemError(err_output)
treepoem.TreepoemError: GPL Ghostscript 9.27: Unrecoverable error, exit code 1

**Comment by adamchainz** [comment]
Hi @UsmanGorsii 

Try checking running `gs` on its own. Also you can modify the library to output the commands it's trying to run and rerun them in the console yourself.

Sorry I can't be of more assistance but whilst I maintain this I am not an expert on how ghostscript works.

Thanks,

Adam
