### ISSUE TITLE
includetext doesn't work on sscc generation

### ISSUE THREAD

**Issue by adsad213** [adamchainz/treepoem#159]
for the options field, we must pass a dictionary

```py
image = treepoem.generate_barcode(barcode_type='sscc18',data="(00)00614141123456789",options={"height":"1"})
```

this works, however, I can't put `options={"includetext"}`, since it needs either an element and True, or "" don't seem to be working.

any clue?

**Comment by dlenski** [comment]
> … since it needs either an element and True

I'm not sure what you're saying here, but did you *try* `True` as the dictionary value? It works.

![image](https://user-images.githubusercontent.com/128716/58068278-96888500-7b45-11e9-8560-94e418ff9e5b.png)

**Comment by adamchainz** [comment]
Thanks for the demo @dlenski
