### ISSUE TITLE
how to set font

### ISSUE THREAD

**Issue by goog** [adamchainz/treepoem#171]
default is /textfont (Courier) def
how to set to "DejaVu Sans Mono"

**Comment by adamchainz** [comment]
Hi,

I believe you can pass `textfont` through to BWIPP in `options`, as per its documentation: https://github.com/bwipp/postscriptbarcode/wiki/Text-Properties

Hope that helps,

Adam

**Comment by goog** [comment]
i have set it, but dont have effect

**Comment by adamchainz** [comment]
Have you tried with other fonts? It might be that DejaVu Sans Mono is just not being discovered by ghostscript / BWIPP for whatever reason. In any case, you can also try with raw ghostscript + BWIPP to check

**Comment by goog** [comment]
@adamchainz  the font not change
![ux-barcode](https://user-images.githubusercontent.com/1488374/61366732-bc6ba500-a8bc-11e9-9ef7-a190f9716ced.png)

**Comment by adamchainz** [comment]
Hi,

Your example missed the `includetext` flag that is also needed.

It works for me on macOS, if I use the example as per the BWIPP wiki: https://github.com/bwipp/postscriptbarcode/wiki/Text-Properties#textfont

```
>>> treepoem.generate_barcode(barcode_type='code128', data='03BG1C0000FB01', options={'includetext': True, 'textfont': 'Times-Roman'}).save('test.png')
```

Results in:

![test](https://user-images.githubusercontent.com/857609/61396413-9b588380-a8bf-11e9-8989-13bbaebb549e.png)

I suspect the font you want is unavailable to postscript, and thus it can't be used by bwipp and the default is used.

Perhaps the ghostscript documentation has more info on finding the list of available fonts.

**Comment by goog** [comment]
thanks a lot!
