### ISSUE TITLE
Ghostscript error

### ISSUE THREAD

**Issue by Kekushke** [adamchainz/treepoem#174]
Previously this has been skirted as a non treepoem issue, but I think this is definitely has to do treepoem not able to obtain correct bounding box while using inherent template. I think other people have also faced the problem, but closing the issue is not solving this problem. Let's keep this open and try to figure out the exact mechanism of what is going on.

```
$ treepoem -o barcode1.png -t gs1datamatrix   "TEST" format=square version=20x20
Traceback (most recent call last):
  File "/home/s/v/bin/treepoem", line 11, in <module>
    sys.exit(main())
  File "/home/s/v/lib/python3.6/site-packages/treepoem/__main__.py", line 62, in main
    image = generate_barcode(args.type, args.data, dict(args.options))
  File "/home/s/v/lib/python3.6/site-packages/treepoem/__init__.py", line 149, in generate_barcode
    bbox_lines = _get_bbox(code)
  File "/home/s/v/lib/python3.6/site-packages/treepoem/__init__.py", line 101, in _get_bbox
    raise TreepoemError(err_output)
treepoem.TreepoemError: GPL Ghostscript 9.26: Unrecoverable error, exit code 1
```

**Comment by Kekushke** [comment]
Also, I can report that 'datamatrix' code construction is not correct, and is not readable by any of the scanners we have. This problem is related to the above  correct construction of the code due to configuration in treepoem templates. I can also confirm that alternate tools elaphe3 is able to construction datamatrix correctly for the identical options. It is most certainly not a problem with BWIPP library, but treepoem. I will be glad to help test out.

Here is the sample test which is the sample command of which created png is not readable by datamatrix readers:
`treepoem -o barcode1.png -t datamatrix "cc96855c-e834-4341-b682-440fd66378c86396de99-d851" format='rectangle' dmre version='12x64'
`

**Comment by adamchainz** [comment]
I guess the previous issue you're referring to is #158 .

I'm afraid I dont' have time to dig into this but please do post your investigation here.

**Comment by adamchainz** [comment]
Closing due to age
