### ISSUE TITLE
Add support custom fonts (for string below barcode)

### ISSUE THREAD

**Issue by pk026** [adamchainz/treepoem#176]
How could use font family Bolonewt? I tried all of  Times-Roman, Times-Italic, Times-Bold, Times-BoldItalic, Helvetica, Helvetica-Oblique, Helvetica-Bold, Helvetica-BoldOblique, Courier, Courier-Oblique, Courier-Bold, Courier-BoldOblique or Symbol. But it turns out that this is not something that we need. we have figured out that we need Bolonewt font family. But I am not able to find a way to use this new font family. Please help.

**Comment by adamchainz** [comment]
Hi @pk026 

I'm afraid I don't know how to expose new fonts to ghostscript. There's some documentation at https://github.com/bwipp/postscriptbarcode/wiki/Text-Properties#textfont about using `fc-scan` - that might help you.

Let me know if you find out anything more, we can document it here then.

Thanks,

Adam

**Comment by adamchainz** [comment]
Closing due to lack of response.
