### ISSUE TITLE
Barcode type 'UPC-A' missing check digit.

### ISSUE THREAD

**Issue by paultuxt** [adamchainz/treepoem#181]
When using UPC-A barcode type, it fails to generate the check digit.
I have tried the options, 'includecheck' and 'includecheckintext', and it generates the barcode missing the check digit.
Example code:
image = tp.generate_barcode(barcode_type='upca', data='73829444752', options={'includetext textsize=5': True,'includecheck': True,'includecheckintext': True, 'addontextxoffset': 10})

When using with barcode_type = 'royalmail', it correctly generates the check digit.

Please help and thank you in advance.

**Comment by adamchainz** [comment]
Hi Paul, I think this will entirely be an issue with upstream BWIPP. Treepoem doesn't do anything special for different kinds of barcodes. Have you tried using BWIPP directly in a postscript file to generate the barcode you want?

**Comment by kevintuxton** [comment]
I am having the same issue. When I used BWIPP web generator, it gives me the barcode with check digit. I tried generating the barcode using treepoem to a PS file but still missing the check digit. Not really sure how to use BWIPP directly in a postscript file to generate the barcode. Can you please give me instructions. Thanks

**Comment by adamchainz** [comment]
Hi,

You can modify treepoem's code to return/print the postscript it generates: https://github.com/adamchainz/treepoem/blob/c2e1568c62d84afceba81cd7783bc24098bcdb47/treepoem/__init__.py#L150

From that, you can manually fiddle with rendering the postscript with ghostscript. There are instructions over in the BWIPP wiki, starting with: https://github.com/bwipp/postscriptbarcode/wiki/Quick-Guide

Thanks,

Adam

**Comment by adamchainz** [comment]
Closing due to lack of response.
