### ISSUE TITLE
Ghostscript v9.26 build fails on PowerPC ppc64le

### ISSUE THREAD

**Issue by aishwaryabk** [adamchainz/treepoem#216]
W.R.T #215 I was trying to build Ghostscript 9.26 on rhel 7.6 ppc64le, However the build fails with the following error:

	./sobin/libgs.so: undefined reference to ``png_init_filter_functions_vsx'`
	`collect2: error: ld returned 1 exit status

`yum install ghostscript` installs ghostscript v9.07 due to which treepoem produces test failures.
Would like some help on this.

**Comment by adamchainz** [comment]
I’m afraid this is outside my realm and I can’t help you. Try red hat or PowerPC forums, or Linux stack exchange.
