### ISSUE TITLE
Modify values at runtime

### ISSUE THREAD

**Issue by misilot** [adamchainz/treepoem#295]
Hi,

is it possible to modify the ```10 10``` value at runtime in this file https://github.com/adamchainz/treepoem/blob/202cd9cacc2ff8017f646e989497be4e33963a76/src/treepoem/__init__.py#L22? as well as the ```2 2 scale``` value?

Thanks!

**Comment by adamchainz** [comment]
only with monkey patching at current

Can you explain your use case?

**Comment by misilot** [comment]
I am trying to make a small and narrow code39 barcode.

I am looking at https://github.com/bwipp/postscriptbarcode/wiki/Resizing-Symbols where it is ```0 0``` instead of ```10 10```, but I think being able to modify the scale value might be more beneficial to me as that seems to at least help augment the shape I am looking for.

For example if you use the Online Generator https://the-burtons.xyz/barcode-generator/

Code39, Options: ```hidestars  height=0.08``` Scale ```1 3``` you get a barcode similiar to 

![image](https://user-images.githubusercontent.com/1446856/106678484-7b131700-6580-11eb-82ed-5d729b7ea201.png)


If you have any other ideas on making it a small narrow barcode that would be great as well. Everything I have tried seems to result in a fairly large image.

Here is what my python looks like

```python
        barcode_image = treepoem.generate_barcode(
            barcode_type='code39',  # One of the BWIPP supported codes.
            data=barcode,
            options={
                'hidestars': True,
                'includecheck': True,
                'includetext': False,
                'includecheckintext': False,
                'height': .08,
            })
```

Thanks!

**Comment by adamchainz** [comment]
I think it would work to add new arguments for these parameters, however I don't have time to write the code. I think we could call the arguments `scale` and `moveto`, as tuples of x, y coordinates, and set the defaults to the current values. Would you be able to write a PR, and check it works in your fork?

**Comment by adamchainz** [comment]
This is no longer required after #499, which should always calculate the bounding box correctly.
