### ISSUE TITLE
Ghostscript crashes when using round brackets in 'alttext' option value

### ISSUE THREAD

**Issue by hazardland** [adamchainz/treepoem#297]
Reproduce - Treepoem 3.3.8 - Ghostscript 9.52

```python
from treepoem import _get_bbox, _format_code

_get_bbox(_format_code('code128', '(01)04860119720024(11)210117', {'alttext':'(01)04860119720024(11)210117'}))

# data = '(01)04860119720024(11)210117'
# data = ']C1'+data.replace('(', '').replace(')', '')

```

Output:
```
Traceback (most recent call last):                                                                                                                                         
  File "gen_barcode.py", line 3, in <module>                                                                                                                               
    _get_bbox(_format_code('code128', '(01)04860119720024(11)210117', {'alttext':'(01)04860119720024(11)210117'}))                                                         
  File "C:\Users\BIOHAZARD\AppData\Local\Programs\Python\Python36\lib\site-packages\treepoem\__init__.py", line 100, in _get_bbox                                          
    raise TreepoemError(err_output)                                                                                                                                        
treepoem.TreepoemError: GPL Ghostscript 9.52: Unrecoverable error, exit code 1  
```

In case of code128 barcode data text needs to be different and must be formatted like this:
```python
data = '(01)04860119720024(11)210117'
_get_bbox(_format_code('code128', ']C1'+data.replace('(', '').replace(')', ''), {'alttext':data}))
```

**Comment by adamchainz** [comment]
Is this really a problem with treepoem? I can imagine we could do some escaping, but you seem to be replacing the brackets with nothing, and not affecting the `alttext`?

**Comment by hazardland** [comment]
@adamchainz I replace brackets for barcode scanner in ```data``` variable and even prepend with string ```]C1``` because for barcode scanners correct output is ```]C1010486011972002411210117``` in case of ```code128``` but human readable text below the barcode still needs to be ```(01)04860119720024(11)210117```. This is achieved by altering ```data``` variable and utilizing ```alttext```.

The fun fact is that if I do not use ```alttext``` and data contains brackets, ghostscript does not crash. So it might mean that ```data``` variable has some kind of escaping and ```alttext``` does not?

**Comment by adamchainz** [comment]
I am afraid I don't know enough about how BWIPP operates to answer these. Please go check in the upstream [repo or docs](https://github.com/bwipp/postscriptbarcode) and report back if there's something we could do in treepoem.

**Comment by hazardland** [comment]
Well it appears for the features I mentioned I should use ```gs1-128``` type instead of ```code128``` and it solves alttext problem and adds specific prefix in encoded data for barcode scanners by itself
