### ISSUE TITLE
Insert FCN1 character into Code128 string

### ISSUE THREAD

**Issue by dev-airterra** [adamchainz/treepoem#321]
Is there a way to insert an FCN1 character into an arbitrary place in a code128 data string prior to encoding?

This code produces the barcode that I want, except that I need an FCN1 character between 42007086 and 92...

tn = '4200708692612903017213001000000091'

image = treepoem.generate_barcode(
    barcode_type='code128',  
    data=tn,
)

**Comment by adamchainz** [comment]
Hi @dev-airterra 

I'm afraid I don't know. This seems like something to check for in the BWIPP docs: https://github.com/bwipp/postscriptbarcode

Btw I googled and found it's FNC1 not FCN1.

Thanks,

Adam

**Comment by adamchainz** [comment]
I found https://github.com/bwipp/postscriptbarcode/wiki/GS1-128 states:

> Note that it is not necessary to specify FNC1 characters since the encoder will insert these automatically where necessary.

**Comment by adamchainz** [comment]
And https://github.com/bwipp/postscriptbarcode/wiki/Code-128:

> When the parsefnc option is specified, non-data function characters can be specified by escape sequences:
> * ^FNC1: FNC1. Recommendation: Use GS1-128 for encoding GS1 AI syntax data.
