### ISSUE TITLE
All generated barcodes have dark backgrounds

### ISSUE THREAD

**Issue by bjrice88** [adamchainz/treepoem#389]
### Description

All barcodes that I generate with Treepoem have been generating more as dark gray and black rather than white and black.  This is even using the `image.convert('1')` conversion.  This does brighten them up very slightly but they are still extremely dark.  This happens for me with any type of barcode.

**Comment by adamchainz** [comment]
I'm afraid I wouldn't really know how to debug this. Have you tried upgrading ghostscript? This may also be a question to ask upstream in BWIPP.

**Comment by bjrice88** [comment]
I appreciate the reply.  After sleeping on it I did fix the issue, and if anyone else runs across this problem on a fresh install I had to explicitly set the `"backgroundcolor"` to `FFFFFF` as an option to generate_barcode for it to work.  Possibly to do with their recent transition from CMYK to RGB?  Not sure but that fixed it for me.
