### ISSUE TITLE
Create PD417 fails

### ISSUE THREAD

**Issue by Dave-DigiMim** [adamchainz/treepoem#394]
### Python Version

3.7.3

### Package Version

3.14.0

### Description

I am trying to create PDF417 with the data below.

I have installed the treepoem package from PyPi and tried
image = treepoem.generate_barcode( barcode_type="pdf417",data=text)
image.convert("1").save("barc.png")

UPDATE I have found that I can have up to 794 characters in the barcode  before this error occurs
But there I get
Error GPL Ghostscript 9.27:Unrecoverable error , exit code 1

text="AZsJRZJwvaYTfBl309+UaA7JyhiSQeb36e50lo0rvxRG6K70iJ8dLtxBPJT2VQqnVSVVSQPud+gCArWp+GA2esgcnnFxQSEvXwqLEw5WDHX2hCscJxhK9lKKhNGBCVE4NDpkTGcZOoriKAX1wYOdQqWDmxnPeYLvD8W8BldrLvaRneKCIaUJj8+z4HET4qBSXRA4EA/Qr1iXpFN0pLwgYu8/gAPSoeRSZNxg9LH4cFBqgQfmOjOB+SnD0Q5Ji8PFv/z2T93c6QKgKS94Whk9LfqJ1PNJFWRFvwkLHGSvESq39uc506hAPh6E3QVJfcWMTWnRBCVfhsjwn+MX03jjcZKlF+q1GEiye0zyI+Lz8r0K3BMVLwM9TaZWDzN8OAKcD5Dh2iUu8tiX/nsKowIeWMCSvUAbRKnXHxDbIGV65IGVTUqsgnM4/VsyPnjfCZ1FmxVIhlzRJVwJPvJIn7ZD0aL+SAGb8lWy76Zj2VclXvBmBjXxA4V17401K8PHbR/j3gTrfoGiCYjEzZzop82ZTdqCSV1AeHVHFvdJvhDrFN3X+ItFAZG+draXyrr76+6CVyNNtlpA8s5gO6sY5n1ngljAGtkPl3TlpG1xqqCYK1JS+N5sCKUMuOGzskjW2hA1/5pg7ZSm1GepM+OMbm44/mLMNih838QJYU+GcihcIGrK/Zq+B96vWVluqyFuY4+PU8XnseaHvOAbUJ7jk2lc71GGD/kyMoIZpBSA3HUTkJ9HW6uKgncbaQeNl6q0lMQMCRfjF4BO1vFOnp5FQWrYmsYrJdLrlQXC+89aXUEWWFb2UBDEH2ZlYECp8FbiPSEQGPLyNRYVy228TN5Rn7vZpWVwPer3TcoMNF7TWHycXcU2mmQypsqdf/jgw/Isd7Vc3gK0BBIKdMMrYzkpu88V7PbDBO6mHHNKORxfG1fVQ2jW7JoXk+ZYhEL4/I4="

**Comment by adamchainz** [comment]
I think this may be a problem for the upstream BWIPP... How many characters is a pdf417 barcode meant to support?

**Comment by Dave-DigiMim** [comment]
Firstly thanks for a great program and your assistance so far. 
   ![barc1](https://user-images.githubusercontent.com/4798359/160760345-b2abf874-48ae-49fe-8428-fd3398f74d6d.png)
ok no sure exactly why but its working now 
this png was made with the following
treepoem -o  barc1.png -t pdf417 "$data" eclevel=1 scale=1 columns=20 rowmult=2 bits=1
its size is  too big for me if I resize, the image is really bad. I have tried scale but it has no effect.
I need to get to 72mm x 17m . Is this possible?

**Comment by adamchainz** [comment]
Try resizing without interpolation.

I'm afraid I can't be much more helpful as I don't use treepoem actively.
