### ISSUE TITLE
Incompatibility with GS10

### ISSUE THREAD

**Issue by francoisdejgr** [adamchainz/treepoem#444]
### Python Version

Python 3.11.0

### Package Version

3.17.0

### Description

Gretings

with gs 10 : I get the following error, **when I installed 9.5.4 no issues**.

treepoem -o barcode1.png -t qrcode "This is a test" eclevel=H

The GS window pops up and if I then close it I get the following message

PS C:\Users\User> treepoem -o barcode1.png -t qrcode "This is a test" eclevel=H
treepoem : Traceback (most recent call last):
At line:1 char:1
+ treepoem -o barcode1.png -t qrcode "This is a test" eclevel=H
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\treepoem.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\treepoem\__main__.py", line 66, in main
    image = generate_barcode(type_, data, options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\treepoem\__init__.py", line 158, in generate_barcode
    bbox_lines = _get_bbox(code)
                 ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\treepoem\__init__.py", line 102, in _get_bbox
    raise TreepoemError(err_output)
treepoem.TreepoemError

**Comment by adamchainz** [comment]
Hi!

I just upgraded the test suite to ghostscript 10.0.0 in #448 and it has no issues.

I cannot easily tell what error you are seeing, since you didn't format the output correctly. Please can you format it properly with three backticks to start/end a code section.

**Comment by francoisdejgr** [comment]
Greetings
If your tests pass, then the issue must be on my side.
Regards
