### ISSUE TITLE
Text under barcode is pixelated and although readable its not very clear

### ISSUE THREAD

**Issue by CDeslatte2023** [adamchainz/treepoem#451]
### Python Version

3.11.1

### Package Version

treepoem             3.18.0

### Description

Is there any way to make the text clearer (more crisp) once rendered? Included a saved PNG as example.

image = treepoem.generate_barcode(barcode_type="sscc18", data=sscc_preliminary, options={'includetext': True, 'textfont': 'Times-Roman'})
        data = io.BytesIO()
image.convert("1").save(data,"PNG")
image.save("barcode.png")

![barcode](https://user-images.githubusercontent.com/122321131/211632748-c9776ac5-0efc-454f-a2a8-34e603d97934.png)

**Comment by adamchainz** [comment]
Sorry, I don't use this library myself atm. I am not sure if there's any way. Try checking the upstream BWIPP documentation.
