### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by LuciferSam8086** [adamchainz/treepoem#510]
### Description

Hello everyone. I have a question for the library. Since treepoem is under MIT, but GhostScript is behind AGPL, does that mean I have to follow the AGPL license?

**Comment by adamchainz** [comment]
I am not a lawyer, but my understanding is that since we only invoke Ghostscript with the BWIPP code, that doesn’t mean you have to share your codebase under the AGPL. Similar to using a GPL database like MariaDB.
