### ISSUE TITLE
test failure on PowerPC ppc64le

### ISSUE THREAD

**Issue by stutiibm** [adamchainz/treepoem#554]
### Python Version

3.9.0

### Package Version

3.24.0

### Description

I am trying to build treepoem on ubi9.3 ppc64le. The build passes, however there is 1 test failure:

ERRORS:
E           assert (4, 134, 202, 152) is None

tests/test_treepoem.py:44: AssertionError
================================================================== short test summary info ==================================================================
FAILED tests/test_treepoem.py::test_barcode[ean13-012345678912-options7] - assert (4, 134, 202, 152) is None
=============================================================== 1 failed, 24 passed in 5.07s ================================================================
py39: exit 1 (5.39 seconds) /treepoem> python -W error::ResourceWarning -W error::DeprecationWarning -W error::PendingDeprecationWarning -m pytest tests pid=134
  py39: FAIL code 1 (12.79=setup[7.40]+cmd[5.39] seconds)
  evaluation failed :( (12.87 seconds)

Python version: Python 3.9
Environment : ubi9.3 ppc64le
Ghostscript 10.03.1

Would like some help on this issue. I am running it on a High end VM with good connectivity.
I am facing same issue on x86 architecture with same python version, ghostscript environment and latest package version 3.24.0

**Comment by adamchainz** [comment]
Hi, I don't support running the test suite outside of the tox setup in this repo (exact Ghostscript version, etc.). Also, I don't care to support rare CPU architectures, but reasonable PRs are welcome to fix any issues.
