### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by xjpf** [adamchainz/treepoem#575]
### Python Version

3.12.7

### Package Version

3.24.0

### Description

Tried on win10 and ubuntu 22.04
Installed ghostscript without any issues
Checked enironments

Still when trying to:
`image = treepoem.generate_barcode(barcode_type='gs1datamatrix', data=somedata)`
on both OS getting:
`treepoem.TreepoemError: bwipp.GS1aiMissingOpenParen AIs must start with '('`

**Comment by adamchainz** [comment]
That's an error from the vendors BWIPP library that the data you're passing is incorrect for that barcode type.
